### ISSUE TITLE
Failed to install v1.0.1 through pip

### ISSUE THREAD

**Issue by zqzten** [orisano/owiener#1]
```sh
pip3 install owiener

Collecting owiener
  Downloading owiener-1.0.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/private/var/folders/rf/_tmcfcsx28b1008cny7sjc6r0000gn/T/pip-build-8wj3tac0/owiener/setup.py", line 7, in <module>
        from m2r import parse_from_file
    ModuleNotFoundError: No module named 'm2r'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/rf/_tmcfcsx28b1008cny7sjc6r0000gn/T/pip-build-8wj3tac0/owiener/setup.py", line 10, in <module>
        with open(readme_file) as f:
    FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/rf/_tmcfcsx28b1008cny7sjc6r0000gn/T/pip-build-8wj3tac0/owiener/README.md'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/rf/_tmcfcsx28b1008cny7sjc6r0000gn/T/pip-build-8wj3tac0/owiener/
```

It seems that the `README.md` required for long description does not exist in your pip repo, which needs a `MANIFEST.in` to include extra files like README. [This question](https://stackoverflow.com/questions/29150804/file-openreadme-in-setup-py-isnt-found) might help.

**Comment by orisano** [comment]
Thanks for the reporting.

fix it.
